"""Shared policy for environment variables exposed to generated tools."""

from __future__ import annotations

import os
import re

DEFAULT_TOOL_ENV_PASSTHROUGH = (
    "BRAVE_SEARCH_API_KEY",
    "NINEROUTER_URL",
    "NINEROUTER_KEY",
)

# These credentials belong to the services themselves and must never be made
# available to bash/python/javascript processes generated by the LLM.
TOOL_ENV_BLOCKLIST = frozenset({
    "EXECUTOR_API_TOKEN",
    "LLM_API_KEY",
    "SUBAGENT_API_TOKEN",
    "SUBAGENT_WEBHOOK_TOKEN",
})

# Non-secret values may be exposed to tools but must not be treated as secret
# material by the main service's output redaction layer.
TOOL_ENV_NON_SECRET = frozenset({"NINEROUTER_URL"})

_RESERVED_PREFIXES = ("AGENT_", "EXECUTOR_", "LLM_", "SUBAGENT_")
_RESERVED_NAMES = frozenset({"FLASK_PORT", "WORKDIR_BASE"})

_ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_tool_env_passthrough(raw: str | None = None) -> tuple[str, ...]:
    """Return validated, de-duplicated tool env names in stable order."""
    if raw is None:
        raw = os.getenv(
            "EXECUTOR_TOOL_ENV_PASSTHROUGH",
            ",".join(DEFAULT_TOOL_ENV_PASSTHROUGH),
        )

    names: list[str] = []
    seen: set[str] = set()
    for item in raw.split(","):
        name = item.strip()
        canonical = name.upper()
        if (
            not name
            or canonical in seen
            or canonical in TOOL_ENV_BLOCKLIST
            or canonical in _RESERVED_NAMES
            or canonical.startswith(_RESERVED_PREFIXES)
            or not _ENV_NAME_RE.fullmatch(name)
        ):
            continue
        seen.add(canonical)
        names.append(name)
    return tuple(names)
